language: node_js
node_js:
    - "0.12"
    - "4.0.0"
before_script: "npm run-script lint"
script: "npm test"
after_success: "./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
